  version: '3.8'

  services:
    postgres:
      container_name: top-cars-postgres
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=top-cars